<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>cantstop.ico</ApplicationIcon>
  </PropertyGroup>


	<PropertyGroup>
		<Version>0.9.0</Version>
	</PropertyGroup>
	
  <ItemGroup>
    <Content Include="cantstop.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
  </ItemGroup>

</Project>
